server:
  port: 100

spring:
  boot:
    admin:
      url: http://localhost:8001
    client:
      service-base-url: http://localhost:8085
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://10.0.0.21:8739/seal_zyzsys_v1.0?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: seal_zyzsys
      password: KsD96M

      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dhht.ftp.model

jiaohu:
  name: 数据交互
  canAddItem: false
  NW_KEY: h9dM6wu3dB7xlVa
  PROCESS_TOTAL_PER_TIME: 200
  TEMP_DATA_DIR: C:/temp
  FTP_HOST: 10.0.0.34
  FTP_PORT: 9000
  FTP_USER: test_ftp
  FTP_PWD: jKa4F9zS1
  FTP_NEW_PATH: /test/new
  FTP_OLD_PATH: /test/old
